site_url: ''
site_name: webЯcade Docs
repo_url: https://github.com/webrcade/webrcade-docs
edit_uri: edit/main/docs/
dev_addr: '127.0.0.1:8080'

nav:
  - About: index.md
  - User Guide:
    - Overview: userguide/index.md
    - User Interface: userguide/interface.md
    - Controls: userguide/controls.md
  - Platforms:
    - Overview: platforms/index.md
    - Windows (PC):
      - Overview: platforms/windows/index.md
    - macOS (Mac): 
      - Overview: platforms/osx/index.md
      - Gamepads: platforms/osx/gamepads.md
    - iOS: 
      - Overview: platforms/ios/index.md
    - Android: 
      - Overview: platforms/android/index.md
    - Xbox Series X|S: 
      - Overview: platforms/xbox/index.md
  - Applications:
    - Overview: apps/index.md
    - Emulators: 
      - Overview: apps/emulators/index.md
      - Atari:
        - 2600: apps/emulators/2600/index.md
        - 7800: apps/emulators/7800/index.md
      - Nintendo:
        - NES: apps/emulators/nes/index.md
        - SNES: apps/emulators/snes/index.md
      - Sega:
        - Master System: apps/emulators/mastersystem/index.md
        - Genesis: apps/emulators/genesis/index.md
        - Game Gear: apps/emulators/gamegear/index.md
    - Engines: 
      - Overview: apps/engines/index.md
      - Classic Doom: apps/engines/doom/index.md
  - Feeds:
    - Overview: feeds/index.md
 
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences  
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg      

plugins:
  - search

extra:  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/webrcade
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/webrcade

extra_css:
  - stylesheets/extra.css

theme:
  copyright: Copyright &copy; 2021 webЯcade
  name: 'material'
  logo: assets/images/webrcade-logo.svg
  palette:
    - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode  
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes    
    - navigation.top






