name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: docker run -v $(pwd)/docs:/docs /docs squidfunk/mkdocs-material build
    - uses: actions/upload-artifact@v1
      with:
        name: site
        path: site